'use client';
import { useState } from 'react';

const VERDICT_THEMES = {
  'Approve': {
    bg: 'bg-emerald-950/40 text-emerald-300 border-emerald-500/40',
    glow: 'shadow-[0_0_20px_-3px_rgba(16,185,129,0.3)]',
    badge: 'bg-emerald-500/20 text-emerald-300',
    icon: '✅'
  },
  'Request Changes': {
    bg: 'bg-rose-950/40 text-rose-300 border-rose-500/40',
    glow: 'shadow-[0_0_20px_-3px_rgba(244,63,94,0.3)]',
    badge: 'bg-rose-500/20 text-rose-300',
    icon: '🚨'
  },
  'Needs Discussion': {
    bg: 'bg-amber-950/40 text-amber-300 border-amber-500/40',
    glow: 'shadow-[0_0_20px_-3px_rgba(245,158,11,0.3)]',
    badge: 'bg-amber-500/20 text-amber-300',
    icon: '⚠️'
  }
};

export default function ReviewOutput({ review }) {
  const verdict = review.verdict || 'Needs Discussion';
  const theme = VERDICT_THEMES[verdict] || VERDICT_THEMES['Needs Discussion'];
  const score = review.score !== undefined ? review.score : 0;
  
  // Custom score ring calculation
  const radius = 32;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (score / 10) * circumference;

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Overview Block */}
      <div className={`glass-panel rounded-2xl p-6 border ${theme.bg} ${theme.glow} transition-all duration-500 flex flex-col md:flex-row items-center md:items-start gap-6 relative overflow-hidden`}>
        {/* Decorative Grid Background */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px] pointer-events-none -z-10"></div>
        
        {/* Left Side: Score Indicator */}
        <div className="flex-shrink-0 flex flex-col items-center justify-center bg-slate-950/40 p-4 rounded-xl border border-white/5 w-32 h-32 relative">
          <svg className="w-24 h-24 transform -rotate-90">
            {/* Background ring */}
            <circle
              cx="48"
              cy="48"
              r={radius}
              stroke="rgba(255, 255, 255, 0.05)"
              strokeWidth="6"
              fill="transparent"
            />
            {/* Progress ring */}
            <circle
              cx="48"
              cy="48"
              r={radius}
              stroke={verdict === 'Approve' ? '#10b981' : verdict === 'Request Changes' ? '#f43f5e' : '#f59e0b'}
              strokeWidth="6"
              strokeDasharray={circumference}
              strokeDashoffset={strokeDashoffset}
              strokeLinecap="round"
              fill="transparent"
              className="transition-all duration-1000 ease-out"
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-3xl font-extrabold text-white tracking-tight">{score}</span>
            <span className="text-[10px] uppercase font-bold text-gray-500 tracking-wider">Score</span>
          </div>
        </div>

        {/* Right Side: Verdict + Summary */}
        <div className="flex-1 space-y-3 text-center md:text-left">
          <div className="flex flex-wrap items-center justify-center md:justify-start gap-3">
            <span className="text-xs uppercase font-bold text-gray-400 tracking-widest">Verdict Assessment</span>
            <span className={`text-xs font-extrabold px-3 py-1 rounded-full border flex items-center gap-1.5 ${theme.badge}`}>
              <span>{theme.icon}</span>
              <span>{verdict}</span>
            </span>
          </div>
          <h4 className="text-white text-xl font-bold tracking-tight">Pull Request Summary</h4>
          <p className="text-gray-300 text-sm md:text-base leading-relaxed max-w-3xl">
            {review.summary || 'No review assessment summary generated by the model.'}
          </p>
        </div>
      </div>

      {/* Critical Issues Collapsible Section */}
      {review.critical && review.critical.length > 0 ? (
        <CollapsibleSection title="🚨 Critical Issues" count={review.critical.length} badgeColor="bg-rose-500/20 text-rose-400 border border-rose-500/30">
          <div className="space-y-4">
            {review.critical.map((item, idx) => (
              <IssueCard
                key={idx}
                file={item.file}
                line={item.line}
                issue={item.issue}
                suggestion={item.suggestion}
                colorTheme="rose"
              />
            ))}
          </div>
        </CollapsibleSection>
      ) : (
        <div className="glass-panel border-white/5 rounded-xl p-4 flex items-center gap-3 text-sm text-emerald-400 bg-emerald-950/10">
          <span>🎉</span>
          <span>No critical logic bugs or safety hazards detected. Great job!</span>
        </div>
      )}

      {/* Warnings Collapsible Section */}
      {review.warnings && review.warnings.length > 0 && (
        <CollapsibleSection title="⚠️ Warnings" count={review.warnings.length} badgeColor="bg-amber-500/20 text-amber-400 border border-amber-500/30">
          <div className="space-y-4">
            {review.warnings.map((item, idx) => (
              <IssueCard
                key={idx}
                file={item.file}
                line={item.line}
                issue={item.issue}
                suggestion={item.suggestion}
                colorTheme="amber"
              />
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Improvements Collapsible Section */}
      {review.improvements && review.improvements.length > 0 && (
        <CollapsibleSection title="💡 Improvements & Best Practices" count={review.improvements.length} badgeColor="bg-sky-500/20 text-sky-400 border border-sky-500/30">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {review.improvements.map((item, idx) => (
              <div key={idx} className="glass-card rounded-xl p-4 hover:border-sky-500/30 transition-all duration-300 flex flex-col gap-2">
                <div className="flex items-center">
                  <span className="text-[10px] uppercase font-bold text-sky-400 bg-sky-950/60 px-2 py-0.5 rounded-md border border-sky-800/40">
                    {item.category || 'Improvement'}
                  </span>
                </div>
                <p className="text-gray-300 text-sm leading-relaxed">{item.suggestion}</p>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Positives List */}
      {review.positives && review.positives.length > 0 && (
        <div className="glass-panel rounded-2xl p-6 border border-white/5 space-y-4 bg-slate-900/20">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <span className="text-emerald-400">✨</span>
            <span>Highlights & Strengths</span>
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
            {review.positives.map((item, idx) => (
              <div key={idx} className="flex gap-2.5 items-start text-sm text-gray-300 bg-slate-900/40 p-3 rounded-lg border border-white/5">
                <span className="text-emerald-400 text-xs mt-1">✔</span>
                <span className="leading-relaxed">{item}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Automated Testing Advice */}
      {review.testingNotes && (
        <div className="glass-panel rounded-2xl p-6 border border-white/5 space-y-3 bg-purple-950/10 border-purple-500/10 relative overflow-hidden">
          <div className="absolute -bottom-10 -right-10 w-24 h-24 bg-purple-500/5 rounded-full blur-2xl"></div>
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <span className="text-purple-400">🧪</span>
            <span>Recommended Testing Strategy</span>
          </h3>
          <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-line pl-1">
            {review.testingNotes}
          </div>
        </div>
      )}
    </div>
  );
}

/* Collapsible Panel Section Utility */
function CollapsibleSection({ title, count, badgeColor, children }) {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <div className="glass-panel rounded-2xl border border-white/5 overflow-hidden transition-all duration-300">
      {/* Header trigger */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-white/[0.02] active:bg-white/[0.01] transition-all"
      >
        <div className="flex items-center gap-3">
          <h3 className="text-base font-bold text-white">{title}</h3>
          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${badgeColor}`}>
            {count}
          </span>
        </div>
        <span className={`text-gray-500 text-xs transition-transform duration-300 ${isOpen ? 'transform rotate-180' : ''}`}>
          ▼
        </span>
      </button>

      {/* Content panel */}
      {isOpen && (
        <div className="px-6 pb-6 pt-1 border-t border-white/5 space-y-4 animate-slide-down">
          {children}
        </div>
      )}
    </div>
  );
}

/* Issue Card Representation */
function IssueCard({ file, line, issue, suggestion, colorTheme }) {
  const theme = {
    rose: {
      border: 'hover:border-rose-500/40',
      badge: 'bg-rose-950/80 text-rose-300 border-rose-800/40',
      line: 'bg-rose-950/60 text-rose-300'
    },
    amber: {
      border: 'hover:border-amber-500/40',
      badge: 'bg-amber-950/80 text-amber-300 border-amber-800/40',
      line: 'bg-amber-950/60 text-amber-300'
    }
  }[colorTheme] || {
    border: 'hover:border-slate-500/40',
    badge: 'bg-slate-900 text-slate-300 border-slate-800',
    line: 'bg-slate-900 text-slate-300'
  };

  return (
    <div className={`glass-card rounded-xl p-4 space-y-3.5 transition-all duration-300 ${theme.border}`}>
      {/* File & Line header badges */}
      <div className="flex flex-wrap items-center gap-2">
        {file && (
          <code className={`text-xs font-mono px-2.5 py-0.5 rounded border ${theme.badge} max-w-full break-all`}>
            📄 {file}
          </code>
        )}
        {line && (
          <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-md ${theme.line}`}>
            Line: {line}
          </span>
        )}
      </div>

      {/* Description */}
      <div className="space-y-2">
        <h5 className="text-white text-sm md:text-base font-bold leading-snug">{issue}</h5>
        {suggestion && (
          <div className="bg-slate-950/50 rounded-lg p-3 border border-white/5 space-y-1.5">
            <span className="text-[10px] font-bold text-gray-500 uppercase tracking-widest block">💬 Suggestion & Fix</span>
            <div className="text-gray-300 text-xs md:text-sm font-medium leading-relaxed whitespace-pre-line">
              {suggestion}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
